set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {C[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {A[0]}]
set_property PACKAGE_PIN M15 [get_ports {A[0]}]
set_property PACKAGE_PIN H17 [get_ports {B[0]}]
set_property PACKAGE_PIN H18 [get_ports {C[0]}]
set_property PACKAGE_PIN W22 [get_ports {D[0]}]
