# Assign inputs/outputs to actual pins on the FPGA
set_property PACKAGE_PIN M15 [get_ports x[0]]
set_property PACKAGE_PIN H17 [get_ports x[1]]
set_property PACKAGE_PIN H18 [get_ports x[2]]
set_property PACKAGE_PIN U14 [get_ports D[0]]
set_property PACKAGE_PIN U19 [get_ports D[1]]
set_property PACKAGE_PIN W22 [get_ports D[2]]
set_property PACKAGE_PIN V22 [get_ports D[3]]
set_property PACKAGE_PIN U21 [get_ports D[4]]
set_property PACKAGE_PIN U22 [get_ports D[5]]
set_property PACKAGE_PIN T21 [get_ports D[6]]
set_property PACKAGE_PIN T22 [get_ports D[7]]

# set voltage levels
set_property IOSTANDARD LVCMOS18 [get_ports x[0]]
set_property IOSTANDARD LVCMOS18 [get_ports x[1]]
set_property IOSTANDARD LVCMOS18 [get_ports x[2]]
set_property IOSTANDARD LVCMOS33 [get_ports D[0]]
set_property IOSTANDARD LVCMOS33 [get_ports D[1]]
set_property IOSTANDARD LVCMOS33 [get_ports D[2]]
set_property IOSTANDARD LVCMOS33 [get_ports D[3]]
set_property IOSTANDARD LVCMOS33 [get_ports D[4]]
set_property IOSTANDARD LVCMOS33 [get_ports D[5]]
set_property IOSTANDARD LVCMOS33 [get_ports D[6]]
set_property IOSTANDARD LVCMOS33 [get_ports D[7]]